version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fhir_postgres
    environment:
      POSTGRES_USER: fhiruser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: patients
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
